import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy - AsaPhisTool',
  description: 'Privacy Policy for AsaPhisTool - Learn how we protect your data and privacy.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-6">
          Privacy Policy
        </h1>
        
        <div className="text-sm text-gray-600 dark:text-gray-400 mb-8">
          Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </div>

        <div className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">1. Introduction</h2>
            <p>
              Welcome to AsaPhisTool ("we," "our," or "us"). We are committed to protecting your privacy 
              and ensuring the security of your personal information. This Privacy Policy explains how we 
              collect, use, disclose, and safeguard your information when you use our online tools platform.
            </p>
            <p className="mt-4">
              <strong>Important:</strong> Most of our tools process data entirely in your browser. Your files 
              and data do not leave your device unless you explicitly use a tool that requires server processing 
              (which will be clearly indicated).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">2. Information We Collect</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2">2.1 Client-Side Processing</h3>
            <p>
              For most of our tools (Image Compressor, PDF Merger, Text Tools, etc.), all processing happens 
              locally in your browser. We do not collect, store, or have access to:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Files you upload or process</li>
              <li>Text content you enter</li>
              <li>Images, PDFs, or other documents you work with</li>
              <li>Results or outputs generated by our tools</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2">2.2 Usage Analytics</h3>
            <p>
              We may collect anonymous usage data to improve our services:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Tool usage statistics (which tools are used, frequency)</li>
              <li>Device type and browser information</li>
              <li>Geographic location (country/region level only)</li>
              <li>Page views and navigation patterns</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2">2.3 Cookies and Local Storage</h3>
            <p>
              We use cookies and local storage for:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Saving your preferences (theme, settings)</li>
              <li>Analytics and performance monitoring</li>
              <li>Essential site functionality</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">3. How We Use Your Information</h2>
            <p>We use the limited information we collect to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Provide and maintain our services</li>
              <li>Improve user experience and tool functionality</li>
              <li>Analyze usage patterns to prioritize new features</li>
              <li>Detect and prevent technical issues</li>
              <li>Comply with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">4. Data Security</h2>
            <p>
              We implement industry-standard security measures to protect your data:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>HTTPS encryption for all connections</li>
              <li>Client-side processing to minimize data transmission</li>
              <li>No storage of user files on our servers (for client-side tools)</li>
              <li>Regular security audits and updates</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">5. Third-Party Services</h2>
            <p>
              We may use third-party services for analytics and functionality:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Google Analytics (anonymized data collection)</li>
              <li>CDN providers for faster content delivery</li>
              <li>Cloud hosting services</li>
            </ul>
            <p className="mt-4">
              These services have their own privacy policies, which we encourage you to review.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">6. Your Rights</h2>
            <p>You have the right to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Access information we hold about you</li>
              <li>Request deletion of your data</li>
              <li>Opt-out of analytics tracking</li>
              <li>Disable cookies in your browser</li>
              <li>Request a copy of your data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">7. Children's Privacy</h2>
            <p>
              Our services are not directed to children under 13. We do not knowingly collect personal 
              information from children under 13. If you believe we have collected such information, 
              please contact us immediately.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">8. International Users</h2>
            <p>
              Our services are accessible worldwide. If you access our services from outside the United States, 
              please be aware that your information may be transferred to, stored, and processed in the 
              United States or other countries.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">9. Changes to This Privacy Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by 
              posting the new Privacy Policy on this page and updating the "Last Updated" date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">10. Contact Us</h2>
            <p>
              If you have questions about this Privacy Policy or our data practices, please contact us:
            </p>
            <div className="mt-4 p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
              <p><strong>Email:</strong> privacy@asaphis.com</p>
              <p className="mt-2"><strong>Website:</strong> <a href="/contact" className="text-primary-600 dark:text-primary-400 hover:underline">Contact Form</a></p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
